-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 11:16:02 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scanner
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scanner` ;

-- -----------------------------------------------------
-- Schema scanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scanner` DEFAULT CHARACTER SET utf8 ;
USE `scanner` ;

-- -----------------------------------------------------
-- Table `scanner`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Place` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Place` (
  `PlaceId` INT NOT NULL,
  `ParentId` INT NULL DEFAULT NULL,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`PlaceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scanner`.`Segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Segment` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Segment` (
  `SegmentId` INT NOT NULL,
  `OriginStation` INT NULL DEFAULT NULL,
  `DestinationStation` INT NULL DEFAULT NULL,
  `DepartureDateTime` VARCHAR(100) NULL DEFAULT NULL,
  `ArrivalDateTime` VARCHAR(100) NULL DEFAULT NULL,
  `CarrierId` INT NULL DEFAULT NULL,
  `OperatingCarrier` INT NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `FlightNumber` INT NULL DEFAULT NULL,
  `Directionality` VARCHAR(100) NULL DEFAULT NULL,
  `PlaceId` INT NOT NULL,
  PRIMARY KEY (`SegmentId`),
  CONSTRAINT `fk_Segment_Place`
    FOREIGN KEY (`PlaceId`)
    REFERENCES `scanner`.`Place` (`PlaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Segments_Places_idx` ON `scanner`.`Segment` (`PlaceId` ASC);


-- -----------------------------------------------------
-- Table `scanner`.`Carrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Carrier` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Carrier` (
  `CarrierId` INT NOT NULL,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `DisplayCode` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CarrierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scanner`.`SegmentLeg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`SegmentLeg` ;

CREATE TABLE IF NOT EXISTS `scanner`.`SegmentLeg` (
  `SegmentLegId` INT NOT NULL,
  `SegmentId` INT NOT NULL,
  PRIMARY KEY (`SegmentLegId`),
  CONSTRAINT `fk_SegmentLeg_Segment1`
    FOREIGN KEY (`SegmentId`)
    REFERENCES `scanner`.`Segment` (`SegmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Segments_has_Legs_Segments1_idx` ON `scanner`.`SegmentLeg` (`SegmentLegId` ASC);

CREATE INDEX `fk_SegmentLeg_Segment1_idx` ON `scanner`.`SegmentLeg` (`SegmentId` ASC);


-- -----------------------------------------------------
-- Table `scanner`.`Leg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Leg` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Leg` (
  `LegId` INT NOT NULL,
  `OriginStation` INT NULL DEFAULT NULL,
  `DestinationStation` INT NULL DEFAULT NULL,
  `Departure` VARCHAR(45) NULL DEFAULT NULL,
  `Arrival` VARCHAR(45) NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `Stops` INT NULL DEFAULT NULL,
  `CarrierId` INT NULL DEFAULT NULL,
  `Directionality` VARCHAR(100) NULL DEFAULT NULL,
  `FlightNumber` VARCHAR(100) NULL DEFAULT NULL,
  `CarrierId` INT NOT NULL,
  `SegmentLegId` INT NOT NULL,
  PRIMARY KEY (`LegId`),
  CONSTRAINT `fk_Legs_Carriers`
    FOREIGN KEY (`CarrierId`)
    REFERENCES `scanner`.`Carrier` (`CarrierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leg_SegmentLeg`
    FOREIGN KEY (`SegmentLegId`)
    REFERENCES `scanner`.`SegmentLeg` (`SegmentLegId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Legs_Carriers1_idx` ON `scanner`.`Leg` (`CarrierId` ASC);

CREATE INDEX `fk_Leg_SegmentLeg1_idx` ON `scanner`.`Leg` (`SegmentLegId` ASC);


-- -----------------------------------------------------
-- Table `scanner`.`PricingOption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`PricingOption` ;

CREATE TABLE IF NOT EXISTS `scanner`.`PricingOption` (
  `PricingOptionId` INT NOT NULL,
  `AgentId` INT NULL,
  `QuoteAgeInMinutes` INT NULL,
  `Price` VARCHAR(45) NULL,
  `DeepLinkUrl` VARCHAR(500) NULL,
  PRIMARY KEY (`PricingOptionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scanner`.`Itinerary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Itinerary` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Itinerary` (
  `ItineraryId` INT NOT NULL,
  `OutboundLegId` VARCHAR(100) NULL DEFAULT NULL,
  `InboundLegId` VARCHAR(100) NULL DEFAULT NULL,
  `PricingOptionId` INT NULL DEFAULT NULL,
  `LegId` INT NOT NULL,
  `PricingOptionId` INT NOT NULL,
  `DateCreated` DATETIME NULL,
  PRIMARY KEY (`ItineraryId`, `OutboundLegId`, `InboundLegId`),
  CONSTRAINT `fk_Itinerary_Legs`
    FOREIGN KEY (`LegId`)
    REFERENCES `scanner`.`Leg` (`LegId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itinerary_PricingOption`
    FOREIGN KEY (`PricingOptionId`)
    REFERENCES `scanner`.`PricingOption` (`PricingOptionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Itinerary_Legs1_idx` ON `scanner`.`Itinerary` (`LegId` ASC);

CREATE INDEX `fk_Itinerary_PricingOption1_idx` ON `scanner`.`Itinerary` (`PricingOptionId` ASC);


-- -----------------------------------------------------
-- Table `scanner`.`Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scanner`.`Agent` ;

CREATE TABLE IF NOT EXISTS `scanner`.`Agent` (
  `AgentId` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `ImageUrl` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `OptimisedForMobile` VARCHAR(45) NULL DEFAULT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `ItineraryId` INT NOT NULL,
  `PricingOptionId` INT NOT NULL,
  PRIMARY KEY (`AgentId`, `Type`),
  CONSTRAINT `fk_Agent_Itinerary`
    FOREIGN KEY (`ItineraryId`)
    REFERENCES `scanner`.`Itinerary` (`ItineraryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agent_PricingOption`
    FOREIGN KEY (`PricingOptionId`)
    REFERENCES `scanner`.`PricingOption` (`PricingOptionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Agents_Itinerary1_idx` ON `scanner`.`Agent` (`ItineraryId` ASC);

CREATE INDEX `fk_Agents_PricingOption1_idx` ON `scanner`.`Agent` (`PricingOptionId` ASC);

CREATE INDEX `fk_Agent_Itinerary` ON `scanner`.`Agent` (`ItineraryId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
